### ISSUE TITLE
Support __set_state on Feature\Map class

### ISSUE THREAD

**Issue by jrbasso** [zumba/swivel#2]
Would be nice to have support to `__set_state` on `Feature\Map` class. This class holds the feature/bucket relations and it can be exported for cache proposes.

**Comment by young-steveo** [comment]
@jrbasso The current iteration of the library abstracts `\Zumba\Swivel\Map` away from the user for pretty much all cases.

What do you think we change this issue to implement `__set_state` on the new map driver system that @cjsaylor will be building?  Those classes are intended for user-land.

**Comment by young-steveo** [comment]
This is resolved by #21 with a small caveat:  If a user injects a logger class that does not implement `__set_state` they will encounter some errors.  However, if no logger is used, the new implementation allows for `__set_state` on the `Map` class.

I'll document this when we tag this change in a release.
